// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ril17ExamsGenerator.Dal;

namespace ril17ExamsGenerator.Migrations
{
    [DbContext(typeof(ExamGeneratorContext))]
    partial class ExamGeneratorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ril17ExamsGenerator.Models.Exam", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("ID");

                    b.ToTable("exams");
                });

            modelBuilder.Entity("ril17ExamsGenerator.Models.History", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("examID");

                    b.HasKey("ID");

                    b.HasIndex("examID");

                    b.ToTable("histories");
                });

            modelBuilder.Entity("ril17ExamsGenerator.Models.Question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ExamID");

                    b.Property<string>("question")
                        .IsRequired();

                    b.Property<int>("type");

                    b.HasKey("ID");

                    b.HasIndex("ExamID");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("ril17ExamsGenerator.Models.Response", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("QuestionID");

                    b.Property<bool>("isCorrect");

                    b.Property<string>("response")
                        .IsRequired();

                    b.HasKey("ID");

                    b.HasIndex("QuestionID");

                    b.ToTable("Response");
                });

            modelBuilder.Entity("ril17ExamsGenerator.Models.History", b =>
                {
                    b.HasOne("ril17ExamsGenerator.Models.Exam", "exam")
                        .WithMany()
                        .HasForeignKey("examID");
                });

            modelBuilder.Entity("ril17ExamsGenerator.Models.Question", b =>
                {
                    b.HasOne("ril17ExamsGenerator.Models.Exam")
                        .WithMany("questions")
                        .HasForeignKey("ExamID");
                });

            modelBuilder.Entity("ril17ExamsGenerator.Models.Response", b =>
                {
                    b.HasOne("ril17ExamsGenerator.Models.Question")
                        .WithMany("responses")
                        .HasForeignKey("QuestionID");
                });
#pragma warning restore 612, 618
        }
    }
}
